version: "8.0.37"

services:
  mysql:
    image: basic-auth:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      # uncomment below if you want to automatically create and select a database
      # MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
